# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.2
_src_path: https://picasso.noviat.com/ci/addons-repo-template.git
ci_exclude_modules: account_asset
ci_image: ghcr.io/oca/oca-ci/py3.8-odoo15.0:latest
customer_slug: Noviat_Generic
odoo_enterprise: 1
odoo_version: 15.0
org_name: Noviat
org_slug: Noviat
repo_name: Modules dedicated to manage the EBICS protocol
repo_slug: accounting-ebics
repo_website: https://www.noviat.com/

